import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";

import Hero from "@/components/Pages/Hero";
import Carousel from "@/components/Pages/Carousel";
import ProfileCard from "@/components/Pages/ProfileCard";
import Recommendations from "@/components/Pages/Recommendations";
import ContactForm from "@/components/Pages/ContactForm";

export default function Home() {
  return (
    <>
      <Head>
        <title>InVerValencia</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
       
      >
       <Hero/>
       <Carousel/>
       <ProfileCard/>
       <Recommendations/>
       <ContactForm/>
      </div>
    </>
  );
}
